"""Infrastructure shared by every Sahaayak service."""

from sahaayak_common.cache import Cache, InMemoryCache, RedisCache, get_cache, reset_cache
from sahaayak_common.contact_crypto import (
    ContactEncryptionUnavailable,
    channel_identity_hash,
    decrypt_destination,
    destination_hash,
    encrypt_destination,
    is_valid_destination,
    is_valid_e164,
    is_valid_email,
    mask_destination,
    normalize_destination,
    reset_encryption_cache,
)
from sahaayak_common.db import engine, get_session, init_db, run_migrations, session_scope
from sahaayak_common.feature_flags import (
    DEFAULT_FEATURE_FLAGS,
    ensure_default_feature_flags,
    feature_flag_enabled,
)
from sahaayak_common.ids import new_id, session_id, slugify, ticket_id, turn_id
from sahaayak_common.logging import configure_logging, get_logger, request_id_var
from sahaayak_common.messaging_budget import BudgetPosture, evaluate_budget, spend_since
from sahaayak_common.models import (
    AuditEvent,
    Benefit,
    BenefitIssueReport,
    CallSession,
    ConsentEvent,
    ContactPoint,
    ConversationTurnLog,
    DataImportRun,
    EscalationTicket,
    EvaluationRun,
    FeatureFlag,
    FeatureFlagRevision,
    Language,
    NotificationDelivery,
    NotificationTemplate,
    ProviderPolicy,
    ProviderPolicyRevision,
    Reminder,
    SavedBenefit,
    State,
    TelemetryEvent,
    UserSession,
)
from sahaayak_common.openai_budget import (
    BudgetError,
    BudgetExceeded,
    BudgetReservation,
    OpenAIBudgetLedger,
)
from sahaayak_common.provider_policy import (
    DEFAULT_PROVIDER_POLICIES,
    get_effective_provider_policy,
)
from sahaayak_common.routing import EscalationRoute, resolve_escalation_route
from sahaayak_common.settings import REPO_ROOT, Settings, get_settings, settings

__all__ = [
    "REPO_ROOT",
    "AuditEvent",
    "Benefit",
    "BenefitIssueReport",
    "BudgetError",
    "BudgetExceeded",
    "BudgetPosture",
    "BudgetReservation",
    "Cache",
    "CallSession",
    "ConsentEvent",
    "ContactEncryptionUnavailable",
    "ContactPoint",
    "ConversationTurnLog",
    "DataImportRun",
    "EvaluationRun",
    "EscalationTicket",
    "FeatureFlag",
    "FeatureFlagRevision",
    "InMemoryCache",
    "Language",
    "NotificationDelivery",
    "NotificationTemplate",
    "OpenAIBudgetLedger",
    "ProviderPolicy",
    "ProviderPolicyRevision",
    "Reminder",
    "SavedBenefit",
    "DEFAULT_PROVIDER_POLICIES",
    "DEFAULT_FEATURE_FLAGS",
    "EscalationRoute",
    "RedisCache",
    "Settings",
    "State",
    "TelemetryEvent",
    "UserSession",
    "channel_identity_hash",
    "configure_logging",
    "decrypt_destination",
    "destination_hash",
    "encrypt_destination",
    "engine",
    "ensure_default_feature_flags",
    "evaluate_budget",
    "get_cache",
    "get_logger",
    "get_effective_provider_policy",
    "get_session",
    "get_settings",
    "init_db",
    "is_valid_destination",
    "is_valid_e164",
    "is_valid_email",
    "mask_destination",
    "new_id",
    "normalize_destination",
    "request_id_var",
    "reset_cache",
    "reset_encryption_cache",
    "resolve_escalation_route",
    "run_migrations",
    "session_id",
    "session_scope",
    "feature_flag_enabled",
    "spend_since",
    "settings",
    "slugify",
    "ticket_id",
    "turn_id",
]
