"""HTTP routes, grouped by what they are for."""

from sahaayak_api.routers import (
    admin,
    admin_directory,
    applications,
    assistance,
    benefit_feedback,
    browser_sessions,
    catalog,
    citizen_identity,
    escalations,
    health,
    households,
    life_events,
    migrations,
    radar,
    rag,
    saved_benefits,
    sessions,
    telephony,
    turns,
    voice_stream,
)

__all__ = [
    "admin",
    "admin_directory",
    "assistance",
    "applications",
    "benefit_feedback",
    "browser_sessions",
    "catalog",
    "citizen_identity",
    "escalations",
    "health",
    "households",
    "life_events",
    "migrations",
    "rag",
    "radar",
    "saved_benefits",
    "sessions",
    "telephony",
    "turns",
    "voice_stream",
]
