/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Languages */
        get: operations["list_languages_api_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List States */
        get: operations["list_states_api_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benefits/{benefit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Benefit Detail
         * @description Return one active benefit and its source/review metadata.
         */
        get: operations["benefit_detail_api_benefits__benefit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Text Turn
         * @description One text turn. The fastest way to exercise the dialogue during a build.
         */
        post: operations["take_text_turn_api_turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Voice Turn
         * @description Audio in, audio out. Shared by the browser demo and any telephony webhook.
         */
        post: operations["take_voice_turn_api_voice_turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rag/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer From Sources */
        post: operations["answer_from_sources_api_rag_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rag/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Sources */
        post: operations["search_sources_api_rag_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browser-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Browser Session */
        post: operations["create_browser_session_api_browser_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session For Caller */
        get: operations["get_session_for_caller_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Reset Session
         * @description Clear a caller's memory.
         *
         *     Needed for demos and re-testing, and it is also the honest answer to
         *     "delete what you know about me" for a service holding income and caste.
         */
        delete: operations["reset_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_sessions__session_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_escalations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escalations/{ticket_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Ticket */
        post: operations["resolve_ticket_api_escalations__ticket_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Me */
        get: operations["admin_me_api_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Overview */
        get: operations["admin_overview_api_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Conversations */
        get: operations["admin_conversations_api_admin_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/telemetry/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Telemetry Events */
        get: operations["admin_telemetry_events_api_admin_telemetry_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/benefits/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Benefit Reviews */
        get: operations["admin_benefit_reviews_api_admin_benefits_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/benefits/{benefit_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Benefit */
        post: operations["review_benefit_api_admin_benefits__benefit_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Imports */
        get: operations["admin_imports_api_admin_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Providers */
        get: operations["admin_providers_api_admin_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/provider-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Provider Policies */
        get: operations["admin_provider_policies_api_admin_provider_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/provider-policies/{provider}/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Provider Policy */
        put: operations["update_provider_policy_api_admin_provider_policies__provider___scope__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/provider-policies/{provider}/{scope}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback Provider Policy */
        post: operations["rollback_provider_policy_api_admin_provider_policies__provider___scope__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Languages */
        get: operations["admin_languages_api_admin_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Audit Events */
        get: operations["admin_audit_events_api_admin_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin System */
        get: operations["admin_system_api_admin_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminMeOut */
        AdminMeOut: {
            /** Actor Id */
            actor_id: string;
            /** Role */
            role: string;
            /** Permissions */
            permissions: string[];
            /** Auth Source */
            auth_source: string;
            /** Mfa Verified */
            mfa_verified: boolean;
        };
        /** AdminOverviewOut */
        AdminOverviewOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Data Fresh At */
            data_fresh_at: string | null;
            /** Partial Data */
            partial_data: boolean;
            /** Window Hours */
            window_hours: number;
            health: components["schemas"]["HealthOut"];
            traffic: components["schemas"]["TrafficOut"];
            quality: components["schemas"]["QualityOut"];
            /** Providers */
            providers: components["schemas"]["ProviderStatusOut"][];
            /** Recent Errors */
            recent_errors: components["schemas"]["RecentErrorOut"][];
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Id */
            id: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Role */
            actor_role: string;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string;
            /** Target Id */
            target_id: string;
            /** Reason */
            reason: string;
            /** Safe Before */
            safe_before: {
                [key: string]: unknown;
            };
            /** Safe After */
            safe_after: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * BenefitDetailOut
         * @description Public benefit details with enough provenance to make trust inspectable.
         */
        BenefitDetailOut: {
            /** Id */
            id: string;
            domain: components["schemas"]["Domain"];
            /** Name */
            name: string;
            /** State Code */
            state_code: string | null;
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Benefits Text */
            benefits_text: string;
            /** Documents Required */
            documents_required: string[];
            /** Application Process */
            application_process: string;
            /** Eligibility Initial */
            eligibility_initial: {
                [key: string]: unknown;
            };
            verification_status: components["schemas"]["VerificationStatus"];
            /** Source Title */
            source_title: string;
            /** Source Document Url */
            source_document_url: string;
            /** Source Excerpt */
            source_excerpt: string | null;
            /** Verified At */
            verified_at: string | null;
            /** Last Verified Date */
            last_verified_date: string | null;
            /** Valid From */
            valid_from: string | null;
            /** Valid Until */
            valid_until: string | null;
        };
        /** BenefitReviewOut */
        BenefitReviewOut: {
            /** Id */
            id: string;
            /** Domain */
            domain: string;
            /** Name */
            name: string;
            /** State Code */
            state_code: string | null;
            /** Verification Status */
            verification_status: string;
            /** Is Active */
            is_active: boolean;
            /** Source Title */
            source_title: string;
            /** Source Document Url */
            source_document_url: string;
            /** Source Excerpt */
            source_excerpt: string | null;
            /** Automated Review */
            automated_review: {
                [key: string]: unknown;
            };
            /** Verified By */
            verified_by: string | null;
            /** Verified At */
            verified_at: string | null;
            /** Last Verified Date */
            last_verified_date: string | null;
            /** Valid From */
            valid_from: string | null;
            /** Valid Until */
            valid_until: string | null;
        };
        /** BenefitReviewRequest */
        BenefitReviewRequest: {
            verification_status: components["schemas"]["VerificationStatus"];
            /** Reason */
            reason: string;
            /** Activate */
            activate?: boolean | null;
        };
        /** Body_take_voice_turn_api_voice_turns_post */
        Body_take_voice_turn_api_voice_turns_post: {
            /** Audio */
            audio: string;
            /** Language Code */
            language_code?: string | null;
            /** State Code */
            state_code?: string | null;
            /**
             * Speak
             * @default true
             */
            speak: boolean;
        };
        /** BrowserSessionOut */
        BrowserSessionOut: {
            /** Session Id */
            session_id: string;
            /** Access Token */
            access_token: string;
            /** Language Code */
            language_code: string;
            /** State Code */
            state_code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** BrowserSessionRequest */
        BrowserSessionRequest: {
            /** Language Code */
            language_code?: string | null;
            /** State Code */
            state_code?: string | null;
        };
        /** ConversationListOut */
        ConversationListOut: {
            /** Items */
            items: components["schemas"]["ConversationSummaryOut"][];
            /** Total */
            total: number;
            /** Data Fresh At */
            data_fresh_at: string | null;
        };
        /** ConversationSummaryOut */
        ConversationSummaryOut: {
            /** Session Key */
            session_key: string;
            /** State Code */
            state_code: string;
            /** Language Code */
            language_code: string;
            /** Turn Count */
            turn_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Contact At
             * Format: date-time
             */
            last_contact_at: string;
            /** Last Intent */
            last_intent: string | null;
        };
        /**
         * CoverageOut
         * @description Benefit counts per state and domain.
         *
         *     Useful in the demo for showing honestly how much data is loaded, rather
         *     than implying nationwide coverage the pipeline has not produced yet.
         */
        CoverageOut: {
            /** By Domain */
            by_domain: {
                [key: string]: number;
            };
            /** By State */
            by_state: {
                [key: string]: number;
            };
            /** Total */
            total: number;
            /** Verified Total */
            verified_total: number;
            /** Illustrative Total */
            illustrative_total: number;
            /** Last Data Update */
            last_data_update?: string | null;
        };
        /**
         * Domain
         * @enum {string}
         */
        Domain: "scheme" | "scholarship" | "job";
        /**
         * EscalationReason
         * @enum {string}
         */
        EscalationReason: "low_confidence" | "caller_requested" | "repeated_misunderstanding" | "no_matches";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Database */
            database: string;
            /** Cache */
            cache: string;
            /** Speech To Text */
            speech_to_text: boolean;
            /** Text To Speech */
            text_to_speech: boolean;
            /** Reasoning Model */
            reasoning_model: boolean;
            /** Tracing */
            tracing: boolean;
            /** Languages */
            languages: string[];
        };
        /** HealthReport */
        HealthReport: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Database */
            database: string;
            /** Cache */
            cache: string;
            /** Speech To Text */
            speech_to_text: boolean;
            /** Text To Speech */
            text_to_speech: boolean;
            /** Reasoning Model */
            reasoning_model: boolean;
            /** Tracing */
            tracing: boolean;
            /** Languages */
            languages: string[];
        };
        /** ImportRunOut */
        ImportRunOut: {
            /** Id */
            id: string;
            /** Source Name */
            source_name: string;
            /** State Code */
            state_code: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Model Name */
            model_name: string;
            /** Prompt Version */
            prompt_version: string;
            /** Input Count */
            input_count: number;
            /** Accepted Count */
            accepted_count: number;
            /** Failed Count */
            failed_count: number;
            /** Review Sample Size */
            review_sample_size: number;
            /** Manifest Json */
            manifest_json: {
                [key: string]: unknown;
            };
        };
        /**
         * Intent
         * @description What the caller wants on this turn.
         *
         *     Separate from `Domain` because several intents are conversational rather
         *     than a request for benefits.
         * @enum {string}
         */
        Intent: "find_scheme" | "find_scholarship" | "find_job" | "ask_about_benefit" | "ask_how_to_apply" | "provide_info" | "request_human" | "greeting" | "unknown";
        /** LanguageOut */
        LanguageOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Native Name */
            native_name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** LanguageReadinessOut */
        LanguageReadinessOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Native Name */
            native_name: string;
            /** Active */
            active: boolean;
            /** Prompt Ready */
            prompt_ready: boolean;
            /** Interface Status */
            interface_status: string;
            /** Data Status */
            data_status: string;
            /** Localized Benefits */
            localized_benefits: number;
            /** Active Benefits */
            active_benefits: number;
            /** Stt Provider */
            stt_provider: string;
            /** Tts Provider */
            tts_provider: string;
            /** Voice Status */
            voice_status: string;
            /** Rollout Status */
            rollout_status: string;
        };
        /**
         * MatchSummary
         * @description A match flattened for the API, without the full criterion trace.
         */
        MatchSummary: {
            /** Benefit Id */
            benefit_id: string;
            /** Benefit Name */
            benefit_name: string;
            domain: components["schemas"]["Domain"];
            /** Verdict */
            verdict: string;
            /** Confidence */
            confidence: number;
            /** Reasons */
            reasons?: string[];
            /** @default illustrative */
            verification_status: components["schemas"]["VerificationStatus"];
            /**
             * Source Title
             * @default
             */
            source_title: string;
            /**
             * Source Document Url
             * @default
             */
            source_document_url: string;
            /** Verified At */
            verified_at?: string | null;
            /** Last Verified Date */
            last_verified_date?: string | null;
        };
        /** ProviderListOut */
        ProviderListOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Providers */
            providers: components["schemas"]["ProviderStatusOut"][];
            /** Policies */
            policies?: components["schemas"]["ProviderPolicyOut"][];
            /** Controls Note */
            controls_note: string;
        };
        /** ProviderPolicyListOut */
        ProviderPolicyListOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Policies */
            policies: components["schemas"]["ProviderPolicyOut"][];
            /** Revisions */
            revisions: components["schemas"]["ProviderPolicyRevisionOut"][];
            /** Controls Note */
            controls_note: string;
        };
        /** ProviderPolicyOut */
        ProviderPolicyOut: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Scope */
            scope: string;
            /** Enabled */
            enabled: boolean;
            /** Primary Provider */
            primary_provider: string;
            /** Fallback Provider */
            fallback_provider: string | null;
            /** Circuit State */
            circuit_state: string;
            /** Daily Budget Usd */
            daily_budget_usd: number | null;
            /** Monthly Budget Usd */
            monthly_budget_usd: number | null;
            /** Override Expires At */
            override_expires_at: string | null;
            /** Revision */
            revision: number;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Updated By */
            updated_by: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProviderPolicyRevisionOut */
        ProviderPolicyRevisionOut: {
            /** Id */
            id: string;
            /** Policy Id */
            policy_id: string;
            /** Revision */
            revision: number;
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Role */
            actor_role: string;
            /** Reason */
            reason: string;
            /** Before */
            before: {
                [key: string]: unknown;
            };
            /** After */
            after: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProviderPolicyRollbackRequest */
        ProviderPolicyRollbackRequest: {
            /** Reason */
            reason: string;
            /** Revision Id */
            revision_id?: string | null;
        };
        /** ProviderPolicyUpdateRequest */
        ProviderPolicyUpdateRequest: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Primary Provider */
            primary_provider: string;
            /** Fallback Provider */
            fallback_provider?: string | null;
            /**
             * Circuit State
             * @default closed
             * @enum {string}
             */
            circuit_state: "closed" | "open" | "half_open";
            /** Daily Budget Usd */
            daily_budget_usd?: number | null;
            /** Monthly Budget Usd */
            monthly_budget_usd?: number | null;
            /** Override Expires At */
            override_expires_at?: string | null;
            /** Reason */
            reason: string;
        };
        /** ProviderStatusOut */
        ProviderStatusOut: {
            /** Name */
            name: string;
            /** Configured */
            configured: boolean;
            /** Health */
            health: string;
            /** Requests */
            requests: number;
            /** Failures */
            failures: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Cache Misses
             * @default 0
             */
            cache_misses: number;
            /** Budget Usd */
            budget_usd?: number | null;
            /** Reserved Usd */
            reserved_usd?: number | null;
            /** Observed Usd */
            observed_usd?: number | null;
            /** Remaining Usd */
            remaining_usd?: number | null;
            /**
             * Controls Available
             * @default false
             */
            controls_available: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** QualityOut */
        QualityOut: {
            /** Escalations */
            escalations: number;
            /** Open Escalations */
            open_escalations: number;
            /** Escalation Rate */
            escalation_rate: number;
            /** No Match Turns */
            no_match_turns: number;
            /** Active Benefits */
            active_benefits: number;
            /** Verified Benefits */
            verified_benefits: number;
            /** Machine Reviewed Benefits */
            machine_reviewed_benefits: number;
            /** Needs Review Benefits */
            needs_review_benefits: number;
            /** Stale Benefits */
            stale_benefits: number;
            /** Illustrative Benefits */
            illustrative_benefits: number;
            /** Latest Import At */
            latest_import_at: string | null;
        };
        /** RagAnswerResponse */
        RagAnswerResponse: {
            /** Query */
            query: string;
            /** Answer */
            answer: string;
            /** Sources */
            sources?: components["schemas"]["RetrievedSource"][];
        };
        /** RagSearchRequest */
        RagSearchRequest: {
            /** Query */
            query: string;
            /**
             * Max Results
             * @default 5
             */
            max_results: number;
            /** Language Code */
            language_code?: string | null;
        };
        /** RagSearchResponse */
        RagSearchResponse: {
            /** Query */
            query: string;
            /** Sources */
            sources?: components["schemas"]["RetrievedSource"][];
        };
        /** RecentErrorOut */
        RecentErrorOut: {
            /** Request Id */
            request_id: string | null;
            /** Route */
            route: string;
            /** Method */
            method: string;
            /** Status Code */
            status_code: number | null;
            /** Error Code */
            error_code: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RetrievedSource */
        RetrievedSource: {
            /** Source Id */
            source_id: string;
            /** Filename */
            filename: string;
            /** Score */
            score: number;
            /** Excerpt */
            excerpt: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /** Attributes */
            attributes?: {
                [key: string]: string | number | boolean;
            };
        };
        /** ReviewQueueOut */
        ReviewQueueOut: {
            /** Items */
            items: components["schemas"]["BenefitReviewOut"][];
            /** Total */
            total: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Data Fresh At */
            data_fresh_at: string | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** State Code */
            state_code: string;
            /** Language Code */
            language_code: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
            /** Conversation State */
            conversation_state?: {
                [key: string]: unknown;
            };
            /** Matched Benefit Ids */
            matched_benefit_ids?: string[];
            /** Turn Count */
            turn_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Contact At
             * Format: date-time
             */
            last_contact_at: string;
        };
        /**
         * SlotName
         * @enum {string}
         */
        SlotName: "age" | "gender" | "social_category" | "annual_family_income" | "education_level" | "occupation" | "enrollment_mode" | "state_residency" | "disability" | "experience_years" | "location";
        /** StateOut */
        StateOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Primary Language Code */
            primary_language_code: string;
            /** Is Active */
            is_active: boolean;
        };
        /** SystemOut */
        SystemOut: {
            /** Environment */
            environment: string;
            /**
             * Process Started At
             * Format: date-time
             */
            process_started_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Git Commit Sha */
            git_commit_sha: string;
            /** Migration Revision */
            migration_revision: string | null;
            /** Database Mode */
            database_mode: string;
            /** Configuration */
            configuration: {
                [key: string]: boolean;
            };
            /** Deployment Notes */
            deployment_notes: string[];
        };
        /** TelemetryEventOut */
        TelemetryEventOut: {
            /** Id */
            id: string;
            /** Event Type */
            event_type: string;
            /** Request Id */
            request_id: string | null;
            /** Trace Id */
            trace_id: string | null;
            /** Trace Url */
            trace_url: string | null;
            /** Route */
            route: string;
            /** Method */
            method: string;
            /** Status Code */
            status_code: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Surface */
            surface: string;
            /** Language Code */
            language_code: string | null;
            /** State Code */
            state_code: string | null;
            /** Provider */
            provider: string | null;
            /** Outcome */
            outcome: string;
            /** Error Code */
            error_code: string | null;
            /** Safe Metadata */
            safe_metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TicketOut */
        TicketOut: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Reason */
            reason: string;
            /** Caller Context */
            caller_context?: {
                [key: string]: unknown;
            };
            /** Transcript Excerpt */
            transcript_excerpt: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** TrafficOut */
        TrafficOut: {
            /** Requests */
            requests: number;
            /** Errors */
            errors: number;
            /** Error Rate */
            error_rate: number;
            /** P50 Latency Ms */
            p50_latency_ms: number;
            /** P95 Latency Ms */
            p95_latency_ms: number;
            /** Active Sessions */
            active_sessions: number;
            /** Turns */
            turns: number;
            /** Language Mix */
            language_mix: {
                [key: string]: number;
            };
        };
        /** TurnOut */
        TurnOut: {
            /** Turn Index */
            turn_index: number;
            /** Role */
            role: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TurnRequest
         * @description A text-mode turn. The voice endpoint builds this after transcription.
         */
        TurnRequest: {
            /** Text */
            text: string;
            /** Language Code */
            language_code?: string | null;
            /** State Code */
            state_code?: string | null;
        };
        /** TurnResponse */
        TurnResponse: {
            /** Session Id */
            session_id: string;
            /** Transcript */
            transcript: string;
            /** Response Text */
            response_text: string;
            /** Grounded Answer */
            grounded_answer?: string | null;
            /** Sources */
            sources?: components["schemas"]["RetrievedSource"][];
            intent: components["schemas"]["Intent"];
            /** Slots */
            slots?: {
                [key: string]: number | string | boolean;
            };
            pending_slot?: components["schemas"]["SlotName"] | null;
            /** Matches */
            matches?: components["schemas"]["MatchSummary"][];
            /**
             * Needs Escalation
             * @default false
             */
            needs_escalation: boolean;
            escalation_reason?: components["schemas"]["EscalationReason"] | null;
            /** Audio Base64 */
            audio_base64?: string | null;
            /** Audio Mime Type */
            audio_mime_type?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationStatus
         * @description How much human review a benefit row has received.
         *
         *     These values are deliberately data rather than Python branches: a new
         *     source row can move through the review lifecycle without changing matcher
         *     logic. Only ``human_verified`` rows are production-ready.
         * @enum {string}
         */
        VerificationStatus: "illustrative" | "machine_structured" | "machine_reviewed" | "needs_review" | "human_verified" | "stale";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    list_languages_api_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"][];
                };
            };
        };
    };
    list_states_api_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"][];
                };
            };
        };
    };
    coverage_api_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"];
                };
            };
        };
    };
    benefit_detail_api_benefits__benefit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                benefit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenefitDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_text_turn_api_turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_voice_turn_api_voice_turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_take_voice_turn_api_voice_turns_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_from_sources_api_rag_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_sources_api_rag_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_browser_session_api_browser_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrowserSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_for_caller_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_sessions__session_id__transcript_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_escalations_get: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_ticket_api_escalations__ticket_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_me_api_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMeOut"];
                };
            };
        };
    };
    admin_overview_api_admin_overview_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_conversations_api_admin_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                state_code?: string | null;
                language_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_telemetry_events_api_admin_telemetry_events_get: {
        parameters: {
            query?: {
                limit?: number;
                event_type?: string | null;
                surface?: string | null;
                route?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_benefit_reviews_api_admin_benefits_review_get: {
        parameters: {
            query?: {
                status?: string | null;
                active?: boolean | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_benefit_api_admin_benefits__benefit_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                benefit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenefitReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenefitReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_imports_api_admin_imports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_providers_api_admin_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListOut"];
                };
            };
        };
    };
    admin_provider_policies_api_admin_provider_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPolicyListOut"];
                };
            };
        };
    };
    update_provider_policy_api_admin_provider_policies__provider___scope__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                scope: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderPolicyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_provider_policy_api_admin_provider_policies__provider___scope__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                scope: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderPolicyRollbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_languages_api_admin_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageReadinessOut"][];
                };
            };
        };
    };
    admin_audit_events_api_admin_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_system_api_admin_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
        };
    };
}
