/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Languages */
        get: operations["list_languages_api_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List States */
        get: operations["list_states_api_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Text Turn
         * @description One text turn. The fastest way to exercise the dialogue during a build.
         */
        post: operations["take_text_turn_api_turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Voice Turn
         * @description Audio in, audio out. Shared by the browser demo and any telephony webhook.
         */
        post: operations["take_voice_turn_api_voice_turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{caller_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session For Caller */
        get: operations["get_session_for_caller_api_sessions__caller_id__get"];
        put?: never;
        post?: never;
        /**
         * Reset Session
         * @description Clear a caller's memory.
         *
         *     Needed for demos and re-testing, and it is also the honest answer to
         *     "delete what you know about me" for a service holding income and caste.
         */
        delete: operations["reset_session_api_sessions__caller_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{caller_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_sessions__caller_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_escalations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escalations/{ticket_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Ticket */
        post: operations["resolve_ticket_api_escalations__ticket_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_take_voice_turn_api_voice_turns_post */
        Body_take_voice_turn_api_voice_turns_post: {
            /** Audio */
            audio: string;
            /** Caller Id */
            caller_id: string;
            /** Language Code */
            language_code?: string | null;
            /** State Code */
            state_code?: string | null;
            /**
             * Speak
             * @default true
             */
            speak: boolean;
        };
        /**
         * CoverageOut
         * @description Benefit counts per state and domain.
         *
         *     Useful in the demo for showing honestly how much data is loaded, rather
         *     than implying nationwide coverage the pipeline has not produced yet.
         */
        CoverageOut: {
            /** By Domain */
            by_domain: {
                [key: string]: number;
            };
            /** By State */
            by_state: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /**
         * Domain
         * @enum {string}
         */
        Domain: "scheme" | "scholarship" | "job";
        /**
         * EscalationReason
         * @enum {string}
         */
        EscalationReason: "low_confidence" | "caller_requested" | "repeated_misunderstanding" | "no_matches";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Database */
            database: string;
            /** Cache */
            cache: string;
            /** Speech To Text */
            speech_to_text: boolean;
            /** Text To Speech */
            text_to_speech: boolean;
            /** Reasoning Model */
            reasoning_model: boolean;
            /** Tracing */
            tracing: boolean;
            /** Languages */
            languages: string[];
        };
        /**
         * Intent
         * @description What the caller wants on this turn.
         *
         *     Separate from `Domain` because several intents are conversational rather
         *     than a request for benefits.
         * @enum {string}
         */
        Intent: "find_scheme" | "find_scholarship" | "find_job" | "ask_about_benefit" | "ask_how_to_apply" | "provide_info" | "request_human" | "greeting" | "unknown";
        /** LanguageOut */
        LanguageOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Native Name */
            native_name: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * MatchSummary
         * @description A match flattened for the API, without the full criterion trace.
         */
        MatchSummary: {
            /** Benefit Id */
            benefit_id: string;
            /** Benefit Name */
            benefit_name: string;
            domain: components["schemas"]["Domain"];
            /** Verdict */
            verdict: string;
            /** Confidence */
            confidence: number;
            /** Reasons */
            reasons?: string[];
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** Phone Or Session Id */
            phone_or_session_id: string;
            /** State Code */
            state_code: string;
            /** Language Code */
            language_code: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
            /** Conversation State */
            conversation_state?: {
                [key: string]: unknown;
            };
            /** Matched Benefit Ids */
            matched_benefit_ids?: string[];
            /** Turn Count */
            turn_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Contact At
             * Format: date-time
             */
            last_contact_at: string;
        };
        /**
         * SlotName
         * @enum {string}
         */
        SlotName: "age" | "gender" | "social_category" | "annual_family_income" | "education_level" | "occupation" | "enrollment_mode" | "state_residency" | "disability" | "experience_years" | "location";
        /** StateOut */
        StateOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Primary Language Code */
            primary_language_code: string;
            /** Is Active */
            is_active: boolean;
        };
        /** TicketOut */
        TicketOut: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Reason */
            reason: string;
            /** Caller Context */
            caller_context?: {
                [key: string]: unknown;
            };
            /** Transcript Excerpt */
            transcript_excerpt: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /** TurnOut */
        TurnOut: {
            /** Turn Index */
            turn_index: number;
            /** Role */
            role: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TurnRequest
         * @description A text-mode turn. The voice endpoint builds this after transcription.
         */
        TurnRequest: {
            /** Caller Id */
            caller_id: string;
            /** Text */
            text: string;
            /** Language Code */
            language_code?: string | null;
            /** State Code */
            state_code?: string | null;
        };
        /** TurnResponse */
        TurnResponse: {
            /** Session Id */
            session_id: string;
            /** Transcript */
            transcript: string;
            /** Response Text */
            response_text: string;
            intent: components["schemas"]["Intent"];
            /** Slots */
            slots?: {
                [key: string]: number | string | boolean;
            };
            pending_slot?: components["schemas"]["SlotName"] | null;
            /** Matches */
            matches?: components["schemas"]["MatchSummary"][];
            /**
             * Needs Escalation
             * @default false
             */
            needs_escalation: boolean;
            escalation_reason?: components["schemas"]["EscalationReason"] | null;
            /** Audio Base64 */
            audio_base64?: string | null;
            /** Audio Mime Type */
            audio_mime_type?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    list_languages_api_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"][];
                };
            };
        };
    };
    list_states_api_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"][];
                };
            };
        };
    };
    coverage_api_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"];
                };
            };
        };
    };
    take_text_turn_api_turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_voice_turn_api_voice_turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_take_voice_turn_api_voice_turns_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_for_caller_api_sessions__caller_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_session_api_sessions__caller_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_sessions__caller_id__transcript_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                caller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_escalations_get: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_ticket_api_escalations__ticket_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
